### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/VocPrez#23]
Vocab > [Collection >] Concept?

Clarify intention with @rob-metalinkage

**Comment by nicholascar** [comment]
From @rob-metalinkage:

I think vocab [ > collection ]* [ > concept]* would be ideal.

this is a suggested ideal scenario:

collections become irrelevant if following relationships , so

If you follow a broader relation then could trim to
vocab > broader > narrower
and highlight broader somehow?

if you follow a relationship to another concept
vocab > concept > (relationship) concept2

if you follow a relationship to a concept in another vocab

vocab > concept > (relationship) > vocab2> concept

**Comment by KoalaGeo** [comment]
In terms of UX/UI Skosmos does this nicely

Can navigate by collection ("groups") in the sidebar, or hierarchy. 

Vocab info - https://finto.fi/yso/en/ (see resource counts at bottom for concept/collection)
Collection - https://finto.fi/yso/en/page/p26567 
Concept - https://finto.fi/yso/en/page/p6898

**Comment by nicholascar** [comment]
Basic Breadcrumbs added to System, Vocabularies, Vocabulary & Concepts default templates. Fancier Breadcrumbs per-implementation, e.g. http://dawe.surroundaustralia.com/

**Comment by rob-metalinkage** [comment]
not seeing breadcrumbs on concepts for that example... only on schemes.

**Comment by nicholascar** [comment]
That implementation doesn't seem to have Concept Breadcrumbs but the base templates now in VP do. We can fix that one as needed for the DAWE work - we will likely do lots of UI fixes on that over the next 2 months.
