### ISSUE TITLE
SKOS Element Browse & Search Pages

### ISSUE THREAD

**Issue by nicholascar** [RDFLib/VocPrez#29]
Create a page for element searching.

Create a page for element browsing.

These are different from vocab listing, as per /vocab/

**On the searching page:**

- search within one vocab
    - via a drop down of all vocabs
- search across all vocabs
- search by type - `Concept` or `Collection` or either

**On the browsing page:**

- list all elements, `Concept` & `Collection`, in all vocabs by starting letter, A, B, C... 

**Links:**

- link to element search & browse in generic index page
- in VocPrez menu
- provide a link per vocab which, when clicked, pre loads the option to search within *this* vocab, i.e. the one you just came from

**Comment by rob-metalinkage** [comment]
Priority is search across all vocabs as a starting point on splash page, and search within vocab on menu bar when viewing a vocab or a concept within one.  

Extension priority 1: add a check box to search all vocabs to within-vocab search

Adding an "advanced search"  link option search boxes  seems necessary for a "searching page" to have a role.?

not sure what a "browsing page" is different to current vocab tree view?

**Comment by nicholascar** [comment]
Addressed in 2.2
