### ISSUE TITLE
Improve UX for concept hierarchy

### ISSUE THREAD

**Issue by rob-metalinkage** [RDFLib/VocPrez#41]
Feedback from user "Users should be informed of the different effects of clicking the triangles and clicking the terms; likewise, the ‘expand all’ option could be signaled visually, and perhaps located below the hierarchy."

**Comment by nicholascar** [comment]
I've changes carets to + & - and made them hyperlinks. Also added more of a note.

Can't put "expand all" below hierarchy as it won't be seen for long hierarchies

https://github.com/RDFLib/VocPrez/commit/9ab9c650b7aea291a4a68e70f8fbe11d22a3154a
