### ISSUE TITLE
Factor out skins from templates

### ISSUE THREAD

**Issue by rob-metalinkage** [RDFLib/VocPrez#9]
The templates duplicate boilerplate skins making customisations rely on full copies - which means improvements wont flow to customisations.
Templates should have a fragments inclusion model so headers, footers and styles get included - or templates themselves are fragments included into a master template (like django templates extend a base) so custom skins only need to be defined once.

**Comment by nicholascar** [comment]
I think this is addressed now: the OGC theming repo only have a template for `index.html` - font page content - and `page.html` site-wide styling.
